pipeline {
    agent {label 'agent'}
    stages{
        stage('Pipeline Stages'){
            steps{
                sh "ls"
            }
        }
        stage('Second Stage'){
            steps {
                sh "pwd"
            }
        }
    }
}